### ISSUE TITLE
12345678, Really?

### ISSUE THREAD

**Issue by kcbence** [Enderbyte-Programs/CraftServerSetup#3]
I get it you want to make money off this but
1. Make keys that aren't "12345678" 
2. Implement a better system than "send $2 CAD to paypal" there are plenty of free alternatives you can do

And also a request try to do a simple gui for it (tkinter)

You seem like a good developer just use cryptography for keys and the appdata folder
I spent 1 minute looking at your code just to find exploits(for key system) even a non that well educated dev could write a crack for this in a few minutes 
I dont wanna say that you are a bad dev, I want to help you no bad intentions
just contact me on discord (@spitkov)

**Comment by Enderbyte09** [comment]
Hello and thank you for your bug report.
Unfortunately, 12345678 is an unfortunate product of the generation algorithm (along with 00000000).
I am very aware of the "exploit." Yes, it is too easy. (Just crash the program, go to the emergency command prompt and run print(generate_product_key()).
The real reason is that I actually care very little about the monetization portion of this software. I could certainly have made it much better (I could have added network key system). 

" there are plenty of free alternatives you can do" : What is an example of that? 

Improve product key cryptography will be put on the TODO list for 0.18.5.

As for the GUI, this program is also intended to be run on desktops and servers and I am not sure that GUI and SSH agree. Also the text-based UI is quite firmly glued in and it would take considerable effort to take away (which I am willing to do for a 2.0)

Thank you very much for your suggestions! You will be contacted on Discord shortly.

**Comment by Enderbyte09** [comment]
12345678 has been discounted as a product key. Further looking into of improved algorithms will be undertaken later.
